---
output: html_document
---

# Reading List

## Readings and Software

There is one required book for the class.

Salganik, M. (2019). Bit by bit: Social research in the digital age. Princeton University Press.

It is a great reference for aspiring computational social scientists, so I recommend you purchase it. That said, I recognize that purchasing books can be a financial hardship, so you can also find a free copy online: https://www.bitbybitbook.com/en/1st-ed/preface/ (Links to an external site.) (Links to an external site.). All other readings can be found in book chapters or journal articles. For many of these, you will be able to download the text from JSTOR (www.JSTOR.org) or another electronic full-text service. Photocopies or PDFs of assigned readings will be made available on Canvas in the Modules section.

Students are expected to bring a computer to lab. We will be using R and RStudio for our analyses. These are free computer software that you can download from https://cran.r-project.org (Links to an external site.) and https://www.rstudio.com (Links to an external site.), respectively.

## Course Outline

The class is divided into sections that run for one week. From the start we spend time in class in discussion (this is not a lecture class!), in exercises to computational social science methods, and in field observation and study, to collect social science data.

## Week 1 (beg. September 20th): Introductions (Lab: Introduction to R)

*For Monday:*
No assignments or readings. Come prepared to say something about yourself and why you are taking this class.

*For Wednesday:*
* Our lab will be a crash course on analyzing data with R
* DUE: Read Bit by Bit, Chapter 1: Introduction
* DUE: Before class, install R and Rstudio, and work through this introductory tutorial on Datacamp: https://campus.datacamp.com/courses/free-introduction-to-r (Links to an external site.)

## Week 2 (beg. September 27th): Ethics (Lab: Surveys and Survey Experiments)

*For Monday:*
* Kramer, A. et al. (2014). Experimental evidence of massive-scale emotional contagion through social networks. PNAS.
* Kiviat, B. (2019). The Moral Limits of Predictive Practices: The Case of Credit-Based Insurance Scores. American Sociological Review, 0003122419884917.

*Optional Reading:* 
* Bit by Bit, Chapter 6: Ethics

*For Wednesday:*
* Our lab will be on surveys and survey experiments. 
* DUE: Complete Lab Exercise 1 by the beginning of class and upload it to Canvas

*Optional Reading:*
* Bit by Bit, Chapter 3: Asking Questions


## Week 3 (beg. October 4th): Inequality (Lab: Collecting Data Online)

*For Monday:*
* Salganik et al. (2006). Experimental study of inequality and unpredictability in an artificial cultural market. Science.
* Adams, J., Brückner, H., & Naslund, C. (2019). Who Counts as a Notable Sociologist on Wikipedia? Gender, Race, and the “Professor Test”. Socius, 5, 2378023118823946.

*For Wednesday:*
* Our lab will be about scraping data and APIs.
* DUE: Complete Lab Exercise 2 by the beginning of class and upload it to Canvas

*Optional Readings:*
Bit by Bit, Chapters 2: Observing Behavior

## Week 4 (beg. October 11th):  Polarization (Lab: Analyzing Text)

*For Monday:*
* Hoffman, M. A. (2019). The Materiality of Ideology: Cultural Consumption and Political Thought after the American Revolution. American Journal of Sociology, 125(1), 1-62.
* Bail, C. A., et al. (2018). Exposure to opposing views on social media can increase political polarization. Proceedings of the National Academy of Sciences, 115(37), 9216-9221.

*For Wednesday:*
* Our lab will be about automated text analysis.
* DUE: Complete Lab Exercise 3 by the beginning of class and upload it to Canvas
* We will sort into groups this week for the final project. Submit your group’s research question and the names of group members to me by Wednesday of next week.

## Week 5 (beg. October 18th):  Markets (Lab: Regression)

*For Monday:*
* Farber, H. (2015). Why you Can't Find a Taxi in the Rain and Other Labor Supply Lessons from Cab Drivers. Quarterly Journal of Economics.
* Fourcade, M. and Healy, K. (2017.) Seeing Like a Market. Socio-Economic Review, 15:9-29.

*For Wednesday:*
* Our lab will be on regression analysis.
* DUE: Submit brief (roughly 1 page) group analysis plan detailing the data you plan to use and your division of labor
* DUE: Complete and email me Lab Exercise 4 by the beginning of class

## Week 6 (beg. October 25th): Discrimination (Lab: Machine Learning)

*For Monday:*
* Garg, N., Schiebinger, L., Jurafsky, D., & Zou, J. (2018). Word embeddings quantify 100 years of gender and ethnic stereotypes. Proceedings of the National Academy of Sciences, 115(16), E3635-E3644.
* Doleac, J. L., & Stein, L. C. (2013). The visible hand: Race and online market outcomes.The Economic Journal, 123(572), F469-F492.
* Karen Hao. (Jan. 21, 2019). AI is sending people to jail, and getting it wrong. MIT Technology Review: https://www.technologyreview.com/s/612775/algorithms-criminal-justice-ai/

*For Wednesday:*
* Our lab will be on machine learning using random forests and neural networks.
* DUE: Complete and email me Lab Exercise 5 by the beginning of class

## Week 7 (beg. November 1st): Homophily and Diffusion (Lab: Network Analysis)

*For Monday:*
* Centola, D. (2010). The spread of behavior in an online social network experiment. Science, 329(5996), 1194-1197.
* Wimmer, A., & Lewis, K. (2010). Beyond and below racial homophily: ERG models of a friendship network documented on Facebook. American Journal of Sociology, 116(2), 583-642.

*For Wednesday:*
* Our lab will be on network analysis.
* DUE: Complete and email me Lab Exercise 6 by the beginning of class

## Week 8 (beg. November 8th):  Semantic Change and Historical Meaning (Lab: Semantic Network Analysis)

*For Monday:*
* Rule, A., Cointet, J. P., & Bearman, P. S. (2015). Lexical shifts, substantive changes, and continuity in State of the Union discourse, 1790–2014. Proceedings of the National Academy of Sciences, 112(35), 10837-10844.
* Murdock, J., Allen, C., & DeDeo, S. (2017). Exploration and exploitation of Victorian science in Darwin’s reading notebooks.Cognition, 159, 117-126.

*Optional Reading:*
* Evans, James A. and Pedro Aceves (2016). "Machine Translation: Mining Text for Social Theory." Annual Review of Sociology.

*For Wednesday:*
* Our lab will be on semantic network analysis.
* No lab exercise due this week.

## Week 9 (beg. November 15th): Health (No Lab)

*For Monday:*
* King, M. D., & Bearman, P. S. (2011). Socioeconomic status and the increased prevalence of autism in California. American sociological review, 76(2), 320-346.
* Eichstaedt, J.C., Smith, R.J., Merchant, R.M., et al. Facebook language predicts depression in medical records. Proceedings of the National Academy of Sciences, 115(44), 11203-11208.

*For Wednesday:*
* Work on your group project
* No lab exercise due this week and no lab either.
* Wednesday’s class will be dedicated to helping you with your projects (think of it as additional office hours/R help sessions)

## Week 10 (beg. November 29th): Group Presentations

## December 11th:  Final papers are due.